In [ ]:
import os
import sys
project_path = os.path.abspath(os.path.join(os.getcwd(),'..'))
sys.path.insert(0,project_path)

#Config and connection testing
from google.cloud import bigquery
from src.config import settings

# For EDA, Data prepareation, Data visulisation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#For network plot
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
from itertools import combinations
from collections import Counter

from datetime import datetime, timedelta
import logging
from typing import List, Dict, Tuple
import warnings
warnings.filterwarnings('ignore')


logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


from src.data_explorer import explor_data

In [ ]:
# #Create dataset
# clinet = bigquery.Client(project=settings.project_id)
# df = clinet.query("""
# SELECT 
#     order_id,
#     order_item_id,
#     order_date,
#     order_time,
#     round(order_total_price / 100,1) as order_total_price,
#     round(order_gst / 100,2) as order_gst,
#     cart_order_time,
# product_name,
# product_variant,
# product_category,
# customer_id,
# first_order_date,
# last_order_date,
# total_orders,
# total_lifetime_value,
# customer_segment
# FROM dbt_medallion_dev_gold.fact_order_items src
# left join dbt_medallion_dev_gold.dim_products dp on src.product_key = dp.product_key
# left join dbt_medallion_dev_gold.dim_customers dc on src.customer_key = dc.customer_key
# order by order_id

# """).to_dataframe()

#Import base df
df = pd.read_csv('../data/raw/data_raw.csv',index_col=0)

In [32]:
df

,order_id,order_item_id,order_date,order_time,order_total_price,order_gst,cart_order_time,product_name,product_variant,product_category,customer_id,first_order_date,last_order_date,total_orders,total_lifetime_value,customer_segment
0,3318,2,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Croissant,Plain,Kitchen,5,2019-05-06,2021-06-05,95,172163,VIP
1,3318,1,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Cappuccino,Regular,Hot Drinks,5,2019-05-06,2021-06-05,95,172163,VIP
2,3318,3,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Iced Coffee with Cream,Regular,Cold Drinks,5,2019-05-06,2021-06-05,95,172163,VIP
3,3319,1,2019-05-26,21:47:03,14.0,1.270000000,1558903500,Croissant,Bacon and Egg,Kitchen,5,2019-05-06,2021-06-05,95,172163,VIP
4,3319,2,2019-05-26,21:47:03,14.0,1.270000000,1558903500,Freshly Squeezed Juice,Regular,Cold Drinks,5,2019-05-06,2021-06-05,95,172163,VIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70509,40641,1,2024-03-06,10:27:19,5.3,0.480000000,ASAP,Flat White,Large,Hot Drinks,261,2020-05-17,2024-03-06,410,304142,VIP
70510,40642,1,2024-03-06,11:07:18,4.8,0.440000000,ASAP,Cappuccino,Large,Hot Drinks,554,2020-11-08,2024-03-06,119,65145,VIP
70511,40643,1,2024-03-06,11:53:26,21.2,1.930000000,ASAP,Coffee Frappe,Regular,Cold Drinks,1192,2022-06-09,2024-03-06,48,111410,VIP
70512,40643,2,2024-03-06,11:53:26,21.2,1.930000000,ASAP,Coffee Frappe,Regular,Cold Drinks,1192,2022-06-09,2024-03-06,48,111410,VIP
70513,40643,3,2024-03-06,11:53:26,21.2,1.930000000,ASAP,Latte,Extra Large,Hot Drinks,1192,2022-06-09,2024-03-06,48,111410,VIP

In [34]:
df

,order_id,order_item_id,order_date,order_time,order_total_price,order_gst,cart_order_time,product_name,product_variant,product_category,customer_id,first_order_date,last_order_date,total_orders,total_lifetime_value,customer_segment
0,3318,2,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Croissant,Plain,Kitchen,5,2019-05-06,2021-06-05,95,172163,VIP
1,3318,1,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Cappuccino,Regular,Hot Drinks,5,2019-05-06,2021-06-05,95,172163,VIP
2,3318,3,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Iced Coffee with Cream,Regular,Cold Drinks,5,2019-05-06,2021-06-05,95,172163,VIP
3,3319,1,2019-05-26,21:47:03,14.0,1.270000000,1558903500,Croissant,Bacon and Egg,Kitchen,5,2019-05-06,2021-06-05,95,172163,VIP
4,3319,2,2019-05-26,21:47:03,14.0,1.270000000,1558903500,Freshly Squeezed Juice,Regular,Cold Drinks,5,2019-05-06,2021-06-05,95,172163,VIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70509,40641,1,2024-03-06,10:27:19,5.3,0.480000000,ASAP,Flat White,Large,Hot Drinks,261,2020-05-17,2024-03-06,410,304142,VIP
70510,40642,1,2024-03-06,11:07:18,4.8,0.440000000,ASAP,Cappuccino,Large,Hot Drinks,554,2020-11-08,2024-03-06,119,65145,VIP
70511,40643,1,2024-03-06,11:53:26,21.2,1.930000000,ASAP,Coffee Frappe,Regular,Cold Drinks,1192,2022-06-09,2024-03-06,48,111410,VIP
70512,40643,2,2024-03-06,11:53:26,21.2,1.930000000,ASAP,Coffee Frappe,Regular,Cold Drinks,1192,2022-06-09,2024-03-06,48,111410,VIP
70513,40643,3,2024-03-06,11:53:26,21.2,1.930000000,ASAP,Latte,Extra Large,Hot Drinks,1192,2022-06-09,2024-03-06,48,111410,VIP

In [38]:
import pandas as pd
import numpy as np
import logging
from typing import Dict, Tuple

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class DataAnalyzer:
    
    def __init__(self, df: pd.DataFrame):
        self.df = df.copy()
        self.logger = logger
        
        required_columns = [
            'order_id', 'order_item_id', 'order_date', 'order_time', 
            'order_total_price', 'order_gst', 'cart_order_time',
            'product_name', 'product_variant', 'product_category',
            'customer_id', 'first_order_date', 'last_order_date',
            'total_orders', 'total_lifetime_value', 'customer_segment'
        ]
        
        missing_cols = set(required_columns) - set(df.columns)
        if missing_cols:
            raise ValueError(f"Missing required columns: {missing_cols}")
            
        self.logger.info("DataAnalyzer initialized successfully")
        
    def analyze_structure(self) -> Dict:
        self.logger.info("="*80)
        self.logger.info("DATA STRUCTURE ANALYSIS")
        self.logger.info("="*80)
        
        self.logger.info(f"Dataset shape: {self.df.shape}")
        self.logger.info(f"Date range: {self.df['order_date'].min()} to {self.df['order_date'].max()}")
        
        for col in self.df.columns:
            dtype = self.df[col].dtype
            null_count = self.df[col].isnull().sum()
            null_pct = (null_count / len(self.df)) * 100
            unique_count = self.df[col].nunique()
            
            self.logger.info(f"{col}: dtype={dtype}, nulls={null_count} ({null_pct:.1f}%), unique={unique_count}")
        
        structure_info = {
            'n_rows': len(self.df),
            'n_cols': len(self.df.columns),
            'date_range': (self.df['order_date'].min(), self.df['order_date'].max())
        }
        
        return structure_info
    
    def analyze_customers(self) -> pd.DataFrame:
        self.logger.info("="*80)
        self.logger.info("CUSTOMER ANALYSIS")
        self.logger.info("="*80)
        
        customer_summary = self.df.groupby('customer_id').agg({
            'order_id': 'nunique',
            'total_orders': 'first',
            'total_lifetime_value': 'first',
            'customer_segment': 'first',
            'first_order_date': 'first',
            'last_order_date': 'first'
        }).reset_index()
        
        self.logger.info(f"Total unique customers: {len(customer_summary)}")
        
        segment_dist = customer_summary['customer_segment'].value_counts()
        self.logger.info("Customer segments:")
        for segment, count in segment_dist.items():
            pct = (count / len(customer_summary)) * 100
            self.logger.info(f"  {segment}: {count} ({pct:.1f}%)")
        
        self.logger.info("Order frequency distribution:")
        self.logger.info(f"{customer_summary['total_orders'].describe()}")
        
        self.logger.info("Lifetime value distribution:")
        self.logger.info(f"{customer_summary['total_lifetime_value'].describe()}")
        
        return customer_summary
    
    def analyze_products(self) -> pd.DataFrame:
        self.logger.info("="*80)
        self.logger.info("PRODUCT ANALYSIS")
        self.logger.info("="*80)
        
        self.logger.info(f"Total unique products: {self.df['product_name'].nunique()}")
        self.logger.info(f"Total unique variants: {self.df['product_variant'].nunique()}")
        
        category_dist = self.df.groupby('product_category').agg({
            'order_id': 'count',
            'product_name': 'nunique'
        }).rename(columns={'order_id': 'order_count', 'product_name': 'unique_products'})
        
        self.logger.info("Product categories:")
        self.logger.info(f"\n{category_dist}")
        
        self.logger.info("Top 15 most popular products:")
        popular_products = self.df.groupby(['product_name', 'product_variant']).size().sort_values(ascending=False).head(15)
        for (product, variant), count in popular_products.items():
            self.logger.info(f"  {product} ({variant}): {count}")
        
        return category_dist
    
    def analyze_temporal_patterns(self) -> Dict:
        self.logger.info("="*80)
        self.logger.info("TEMPORAL PATTERN ANALYSIS")
        self.logger.info("="*80)
        
        self.df['order_datetime'] = pd.to_datetime(
    df['order_date'].astype(str) + ' ' + df['order_time'].astype(str)
)
        self.df['hour'] = self.df['order_datetime'].dt.hour
        self.df['day_of_week'] = self.df['order_datetime'].dt.dayofweek
        
        hourly = self.df.groupby('hour')['order_id'].nunique().sort_values(ascending=False)
        self.logger.info("Orders by hour of day (top 5):")
        for hour, count in hourly.head(5).items():
            self.logger.info(f"  {hour:02d}:00 - {count} orders")
        
        days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        daily = self.df.groupby('day_of_week')['order_id'].nunique()
        self.logger.info("Orders by day of week:")
        for day_idx, count in daily.items():
            self.logger.info(f"  {days[day_idx]}: {count} orders")
        
        temporal_info = {
            'peak_hour': hourly.idxmax(),
            'peak_day': days[daily.idxmax()]
        }
        
        return temporal_info
    
    def check_data_quality(self) -> Dict:
        self.logger.info("="*80)
        self.logger.info("DATA QUALITY CHECKS")
        self.logger.info("="*80)
        
        issues = []
        
        duplicates = self.df.duplicated().sum()
        if duplicates > 0:
            issues.append(f"Found {duplicates} duplicate rows")
            self.logger.warning(f"Found {duplicates} duplicate rows")
        else:
            self.logger.info("No duplicate rows found")
        
        product_category_check = self.df.groupby('product_name')['product_category'].nunique()
        inconsistent = product_category_check[product_category_check > 1]
        if len(inconsistent) > 0:
            issues.append(f"{len(inconsistent)} products with multiple categories")
            self.logger.warning(f"{len(inconsistent)} products have inconsistent categories")
        else:
            self.logger.info("Product categories are consistent")
        
        negative_prices = (self.df['order_total_price'] < 0).sum()
        if negative_prices > 0:
            issues.append(f"{negative_prices} orders with negative prices")
            self.logger.warning(f"{negative_prices} orders with negative prices")
        else:
            self.logger.info("All prices are valid")
        
        quality_report = {
            'duplicates': duplicates,
            'inconsistent_categories': len(inconsistent),
            'negative_prices': negative_prices,
            'issues': issues
        }
        
        if len(issues) == 0:
            self.logger.info("Data quality checks passed")
        
        return quality_report
    
    def analyze_recommendation_feasibility(self) -> Dict:
        self.logger.info("="*80)
        self.logger.info("RECOMMENDATION SYSTEM FEASIBILITY")
        self.logger.info("="*80)
        
        customers_with_history = self.df.groupby('customer_id')['order_id'].nunique()
        sufficient_history = (customers_with_history >= 3).sum()
        self.logger.info(f"Customers with 3+ orders: {sufficient_history} ({sufficient_history/len(customers_with_history)*100:.1f}%)")
        
        avg_unique_products = self.df.groupby('customer_id')['product_name'].nunique().mean()
        total_products = self.df['product_name'].nunique()
        self.logger.info(f"Average products per customer: {avg_unique_products:.1f}")
        self.logger.info(f"Total available products: {total_products}")
        self.logger.info(f"Average unexplored products per customer: {total_products - avg_unique_products:.1f}")
        
        customer_product_matrix = self.df.groupby(['customer_id', 'product_name']).size().unstack(fill_value=0)
        sparsity = 1 - (customer_product_matrix.astype(bool).sum().sum() / (customer_product_matrix.shape[0] * customer_product_matrix.shape[1]))
        self.logger.info(f"User-item matrix shape: {customer_product_matrix.shape}")
        self.logger.info(f"Matrix sparsity: {sparsity * 100:.1f}%")
        
        feasibility_report = {
            'sufficient_history_pct': sufficient_history/len(customers_with_history),
            'avg_products_per_customer': avg_unique_products,
            'total_products': total_products,
            'matrix_sparsity': sparsity
        }
        
        return feasibility_report
    
    def generate_summary(self) -> Dict:
        self.logger.info("="*80)
        self.logger.info("SUMMARY REPORT")
        self.logger.info("="*80)
        
        summary = {
            'total_records': len(self.df),
            'unique_customers': self.df['customer_id'].nunique(),
            'unique_products': self.df['product_name'].nunique(),
            'unique_orders': self.df['order_id'].nunique(),
            'date_range': (self.df['order_date'].min(), self.df['order_date'].max()),
            'avg_items_per_order': len(self.df) / self.df['order_id'].nunique(),
            'avg_orders_per_customer': self.df.groupby('customer_id')['order_id'].nunique().mean()
        }
        
        self.logger.info(f"Total records: {summary['total_records']:,}")
        self.logger.info(f"Unique customers: {summary['unique_customers']:,}")
        self.logger.info(f"Unique products: {summary['unique_products']}")
        self.logger.info(f"Unique orders: {summary['unique_orders']:,}")
        self.logger.info(f"Date range: {summary['date_range'][0]} to {summary['date_range'][1]}")
        self.logger.info(f"Average items per order: {summary['avg_items_per_order']:.2f}")
        self.logger.info(f"Average orders per customer: {summary['avg_orders_per_customer']:.2f}")
        
        return summary
    
    def run_analysis(self) -> Dict:
        structure_info = self.analyze_structure()
        customer_summary = self.analyze_customers()
        product_summary = self.analyze_products()
        temporal_info = self.analyze_temporal_patterns()
        quality_report = self.check_data_quality()
        feasibility_report = self.analyze_recommendation_feasibility()
        summary = self.generate_summary()
        
        self.logger.info("="*80)
        self.logger.info("STEP 1 COMPLETE")
        self.logger.info("="*80)
        
        return {
            'structure': structure_info,
            'customer_summary': customer_summary,
            'product_summary': product_summary,
            'temporal': temporal_info,
            'quality': quality_report,
            'feasibility': feasibility_report,
            'summary': summary
        }


if __name__ == "__main__":
    logger.info("STEP 1: Data Analysis and Understanding")
    logger.info("Usage: analyzer = DataAnalyzer(df)")
    logger.info("       results = analyzer.run_analysis()")

2025-11-23 15:45:12,203 - __main__ - INFO - STEP 1: Data Analysis and Understanding
2025-11-23 15:45:12,203 - __main__ - INFO - Usage: analyzer = DataAnalyzer(df)
2025-11-23 15:45:12,203 - __main__ - INFO -        results = analyzer.run_analysis()

In [39]:
analyzer = DataAnalyzer(df)

2025-11-23 15:45:12,478 - __main__ - INFO - DataAnalyzer initialized successfully

In [ ]:
class DataPreparation:
    
    def __init__(self, df: pd.DataFrame):
        self.df = df.copy()
        self.logger = logger
        self.original_shape = df.shape

    def remove_duplicates(self):
        initial_rows = len(self.df)
        self.df = self.df.drop_duplicates()
        removed = initial_rows - len(self.df)

        self.logger.info(f"Removed {removed} duplicate rows")

    def handle_missing_values(self):
        null_counts = self.df.isnull().sum()
        cols_with_nulls = null_counts[null_counts > 0]

        if len(cols_with_nulls)> 0:
            self.logger.info("Columns with missing values:")
            for col, count in cols_with_nulls.items():
                pct = (count / len(self.df)) * 100
                self.logger.info(f"  {col}: {count} ({pct:.1f}%)")
        else:
            self.logger.info(f"No missing value found")
        #Sepcial handler for product variant
        if 'product_variant' in cols_with_nulls.index:
            self.df['product_variant'].fillna('Regular', inplace=True)
            self.logger.info("Filled missing product_variant with 'Regular'")
        if 'order_gst' in cols_with_nulls.index:
            self.df['order_gst'].fillna(0, inplace=True)
            self.logger.info("Filled missing order_gst with 0")
        return self
    
    def validate_product_categories(self) -> 'DataPreparation':
        
        product_category_map = self.df.groupby('product_name')['product_category'].agg(
            lambda x: x.mode()[0] if len(x.mode()) > 0 else x.iloc[0]
        ).to_dict()
        
        inconsistent_products = self.df.groupby('product_name')['product_category'].nunique()
        inconsistent_products = inconsistent_products[inconsistent_products > 1]
        
        if len(inconsistent_products) > 0:
            self.logger.info(f"Found {len(inconsistent_products)} products with inconsistent categories")
            self.logger.info("Fixing inconsistent categories using most frequent value")
            
            for product in inconsistent_products.index:
                correct_category = product_category_map[product]
                mask = self.df['product_name'] == product
                self.df.loc[mask, 'product_category'] = correct_category
            
            self.logger.info("Fixed all inconsistent product categories")
        else:
            self.logger.info("All product categories are consistent")
        
        return self
    
    def validate_prices(self):
        negative_prices = self.df[self.df['order_total_price'] < 0]
        if len(negative_prices) > 0:
            self.logger.warning(f"Found {len(negative_prices)} orders with negative prices")
            self.df = self.df[self.df['order_total_price'] >= 0]
            self.logger.info(f"Removed orders with negative prices")
        else:
            self.logger.info("All prices are valid")
        
        zero_prices = self.df[self.df['order_total_price'] == 0]
        if len(zero_prices) > 0:
            self.logger.warning(f"Found {len(zero_prices)} orders with zero price")
            self.df = self.df[self.df['order_total_price'] > 0]
            self.logger.info(f"Removed orders with zero price")
        
        return self
    def create_composite_features(self):
        
        self.df['product_full'] = self.df['product_name'] + '_' + self.df['product_variant']
        self.logger.info("Created product_full: product_name + product_variant")
        
        self.df['order_datetime'] = pd.to_datetime(
    df['order_date'].astype(str) + ' ' + df['order_time'].astype(str)
)
        self.logger.info("Created order_datetime from order_date and order_time")
        
        self.df['hour'] = self.df['order_datetime'].dt.hour
        self.df['day_of_week'] = self.df['order_datetime'].dt.dayofweek
        self.df['month'] = self.df['order_datetime'].dt.month
        self.df['year'] = self.df['order_datetime'].dt.year
        self.logger.info("Created temporal features: hour, day_of_week, month, year")
        
        self.df['is_weekend'] = self.df['day_of_week'].isin([5, 6]).astype(int)
        self.logger.info("Created is_weekend feature")
        
        return self
    
    def sort_by_datetime(self) -> 'DataPreparation':
        
        self.df = self.df.sort_values(['customer_id', 'order_datetime'])
        self.df = self.df.reset_index(drop=True)
        self.logger.info("Sorted by customer_id and order_datetime")
        
        return self
    
    def validate_customer_features(self) -> 'DataPreparation':
        
        inconsistent_ltv = self.df.groupby('customer_id')['total_lifetime_value'].nunique()
        inconsistent_ltv = inconsistent_ltv[inconsistent_ltv > 1]
        
        if len(inconsistent_ltv) > 0:
            self.logger.warning(f"Found {len(inconsistent_ltv)} customers with inconsistent lifetime values")
            
            customer_ltv_map = self.df.groupby('customer_id')['total_lifetime_value'].max().to_dict()
            for customer_id, ltv in customer_ltv_map.items():
                self.df.loc[self.df['customer_id'] == customer_id, 'total_lifetime_value'] = ltv
            
            self.logger.info("Fixed inconsistent lifetime values using maximum value")
        else:
            self.logger.info("Customer lifetime values are consistent")
        
        return self
    
    def generate_cleaning_report(self) -> dict:
        
        report = {
            'original_rows': self.original_shape[0],
            'final_rows': len(self.df),
            'rows_removed': self.original_shape[0] - len(self.df),
            'removal_percentage': ((self.original_shape[0] - len(self.df)) / self.original_shape[0]) * 100,
            'unique_customers': self.df['customer_id'].nunique(),
            'unique_products': self.df['product_name'].nunique(),
            'unique_orders': self.df['order_id'].nunique(),
            'date_range': (self.df['order_date'].min(), self.df['order_date'].max())
        }
        
        self.logger.info(f"Original rows: {report['original_rows']:,}")
        self.logger.info(f"Final rows: {report['final_rows']:,}")
        self.logger.info(f"Rows removed: {report['rows_removed']:,} ({report['removal_percentage']:.2f}%)")
        self.logger.info(f"Unique customers: {report['unique_customers']:,}")
        self.logger.info(f"Unique products: {report['unique_products']}")
        self.logger.info(f"Unique orders: {report['unique_orders']:,}")
        
        return report
    def run_preparation(self) -> Tuple[pd.DataFrame, dict]:
        
        self.remove_duplicates()
        self.handle_missing_values()
        self.validate_product_categories()
        self.validate_prices()
        self.validate_customer_features()
        self.create_composite_features()
        self.sort_by_datetime()
        
        report = self.generate_cleaning_report()
        
        self.logger.info("="*80)
        self.logger.info("Data is now clean")
        self.logger.info("="*80)
        return self.df, report

In [60]:
clean_df['product_full']

0                       Croissant_Plain
1                    Cappuccino_Regular
2        Iced Coffee with Cream_Regular
3               Croissant_Bacon and Egg
4        Freshly Squeezed Juice_Regular
                      ...
70509                Cappuccino_Regular
70510                  Cappuccino_Large
70511                  Cappuccino_Large
70512                  Flat White_Large
70513             Hot Chocolate_Regular
Name: product_full, Length: 70514, dtype: object

In [64]:
clean_df.groupby(['customer_id', 'product_full']).size().reset_index(name='interaction_count')

      customer_id                           product_full  interaction_count
0               5    (Entree) Pasta_E Funghi Avocado (V)                  1
1               5               (Entree) Pasta_Mona Lisa                  2
2               5       (Main) Pasta_Spaghetti Bolognese                  1
3               5      (Main) Pasta_Spaghetti Matriciana                  1
4               5  (Main) Pasta_Spaghetti Napolitana (V)                  1
...           ...                                    ...                ...
9035         1755                     Cappuccino_Regular                  1
9036         1756                       Cappuccino_Large                  1
9037         1757                       Cappuccino_Large                  1
9038         1758                       Flat White_Large                  1
9039         1758                  Hot Chocolate_Regular                  1

[9040 rows x 3 columns]

In [68]:
user_item_matrix = interactions.pivot_table(
            index='customer_id',
            columns='product_full',
            values='interaction_count',
            fill_value=0)

In [69]:
sparsity = 1 - (user_item_matrix.astype(bool).sum().sum() / 
                        (user_item_matrix.shape[0] * user_item_matrix.shape[1]))

In [70]:
sparsity

np.float64(0.9792198239201895)

In [71]:
user_features = clean_df.groupby('customer_id').agg({
            'order_id': 'nunique',
            'order_datetime': ['min', 'max'],
            'order_total_price': ['sum', 'mean', 'std'],
            'total_orders': 'first',
            'total_lifetime_value': 'first',
            'customer_segment': 'first',
            'first_order_date': 'first',
            'last_order_date': 'first',
            'hour': lambda x: x.mode()[0] if len(x.mode()) > 0 else x.mean(),
            'day_of_week': lambda x: x.mode()[0] if len(x.mode()) > 0 else x.mean(),
            'is_weekend': 'mean'
        })
user_features

            order_id      order_datetime                      \
             nunique                 min                 max
customer_id
5                 52 2019-05-26 13:17:13 2021-06-05 17:42:20
6                  2 2020-07-23 09:39:33 2023-08-08 09:58:48
7                  1 2019-05-31 13:59:19 2019-05-31 13:59:19
8                161 2019-06-01 08:31:18 2023-10-14 13:57:55
9               1027 2019-06-02 12:26:44 2024-03-05 10:35:52
...              ...                 ...                 ...
1754               1 2024-03-04 08:34:44 2024-03-04 08:34:44
1755               1 2024-03-04 15:38:37 2024-03-04 15:38:37
1756               1 2024-03-05 08:07:48 2024-03-05 08:07:48
1757               1 2024-03-06 08:00:06 2024-03-06 08:00:06
1758               1 2024-03-06 08:41:38 2024-03-06 08:41:38

            order_total_price                         total_orders  \
                          sum        mean         std        first
customer_id
5                     23846.4  141.102959  171.333740           95
6                        98.9   19.780000    7.870959            4
7                        39.3   13.100000    0.000000            1
8                      3269.9   12.066052    9.864956          162
9                     25513.2   13.413880    6.153317         1028
...                       ...         ...         ...          ...
1754                      5.3    5.300000         NaN            1
1755                      4.2    4.200000         NaN            1
1756                      4.8    4.800000         NaN            1
1757                      4.8    4.800000         NaN            1
1758                     20.6   10.300000    0.000000            1

            total_lifetime_value customer_segment first_order_date  \
                           first            first            first
customer_id
5                         172163              VIP       2019-05-06
6                           5297          Regular       2019-05-07
7                           1310              New       2019-05-31
8                         147700              VIP       2019-06-01
9                        1174285              VIP       2019-06-02
...                          ...              ...              ...
1754                         530              New       2024-03-04
1755                         420              New       2024-03-04
1756                         480              New       2024-03-05
1757                         480              New       2024-03-06
1758                        1030              New       2024-03-06

            last_order_date     hour day_of_week is_weekend
                      first <lambda>    <lambda>       mean
customer_id
5                2021-06-05       23           4   0.147929
6                2023-08-08        9           1   0.000000
7                2019-05-31       13           4   0.000000
8                2023-10-14        7           4   0.243542
9                2024-03-05       10           5   0.293901
...                     ...      ...         ...        ...
1754             2024-03-04        8           0   0.000000
1755             2024-03-04       15           0   0.000000
1756             2024-03-05        8           1   0.000000
1757             2024-03-06        8           2   0.000000
1758             2024-03-06        8           2   0.000000

[1706 rows x 14 columns]

In [72]:
import pandas as pd
import numpy as np
import logging
from scipy.sparse import csr_matrix
from typing import Tuple, Dict, List
from collections import Counter

class OrderLevelFeatureEngineering:
    
    def __init__(self, df: pd.DataFrame):
        self.df = df.copy()
        self.logger = logger
        
        self.user_item_matrix = None
        self.user_features = None
        self.item_features = None
        self.sequential_data = None
        
        self.logger.info("Order-Level Feature Engineering initialized")
        
    def create_user_item_matrix(self) -> 'OrderLevelFeatureEngineering':

        
        interactions = self.df.groupby(['customer_id', 'product_full']).size().reset_index(name='interaction_count')
        
        self.user_item_matrix = interactions.pivot_table(
            index='customer_id',
            columns='product_full',
            values='interaction_count',
            fill_value=0
        )
        
        sparsity = 1 - (self.user_item_matrix.astype(bool).sum().sum() / 
                        (self.user_item_matrix.shape[0] * self.user_item_matrix.shape[1]))
        
        self.logger.info(f"Matrix shape: {self.user_item_matrix.shape}")
        self.logger.info(f"Sparsity: {sparsity*100:.2f}%")
        
        return self
    
    def create_user_features(self) -> 'OrderLevelFeatureEngineering':
        self.logger.info("="*80)
        self.logger.info("CREATING USER FEATURES")
        self.logger.info("="*80)
        
        user_features = self.df.groupby('customer_id').agg({
            'order_id': 'nunique',
            'order_datetime': ['min', 'max'],
            'order_total_price': ['sum', 'mean', 'std'],
            'total_orders': 'first',
            'total_lifetime_value': 'first',
            'customer_segment': 'first',
            'first_order_date': 'first',
            'last_order_date': 'first',
            'hour': lambda x: x.mode()[0] if len(x.mode()) > 0 else x.mean(),
            'day_of_week': lambda x: x.mode()[0] if len(x.mode()) > 0 else x.mean(),
            'is_weekend': 'mean'
        })
        
        user_features.columns = ['_'.join(col).strip() if col[1] else col[0] 
                                 for col in user_features.columns.values]
        
        user_features = user_features.rename(columns={
            'order_id_nunique': 'unique_orders',
            'order_datetime_min': 'first_order_datetime',
            'order_datetime_max': 'last_order_datetime',
            'order_total_price_sum': 'total_spent',
            'order_total_price_mean': 'avg_order_value',
            'order_total_price_std': 'order_value_std',
            'total_orders_first': 'total_orders',
            'total_lifetime_value_first': 'lifetime_value',
            'customer_segment_first': 'segment',
            'first_order_date_first': 'first_order_date',
            'last_order_date_first': 'last_order_date',
            'hour_<lambda>': 'preferred_hour',
            'day_of_week_<lambda>': 'preferred_day',
            'is_weekend_mean': 'weekend_preference'
        })
        
        user_features['customer_lifetime_days'] = (
            user_features['last_order_datetime'] - user_features['first_order_datetime']
        ).dt.days + 1
        
        user_features['order_frequency'] = user_features['unique_orders'] / user_features['customer_lifetime_days']
        user_features['order_value_std'].fillna(0, inplace=True)
        user_features['avg_items_per_order'] = self.df.groupby('customer_id').size() / user_features['unique_orders']
        user_features['unique_products'] = self.df.groupby('customer_id')['product_name'].nunique()
        user_features['unique_categories'] = self.df.groupby('customer_id')['product_category'].nunique()
        
        self.user_features = user_features
        
        self.logger.info(f"Created {len(user_features.columns)} user features")
        
        return self
    
    def create_item_features(self) -> 'OrderLevelFeatureEngineering':
        self.logger.info("="*80)
        self.logger.info("CREATING ITEM FEATURES")
        self.logger.info("="*80)
        
        item_features = self.df.groupby('product_full').agg({
            'product_name': 'first',
            'product_variant': 'first',
            'product_category': 'first',
            'order_id': 'nunique',
            'customer_id': 'nunique',
            'order_total_price': 'mean',
            'hour': lambda x: x.mode()[0] if len(x.mode()) > 0 else x.mean(),
            'is_weekend': 'mean'
        }).rename(columns={
            'product_name': 'name',
            'product_variant': 'variant',
            'product_category': 'category',
            'order_id': 'total_orders',
            'customer_id': 'unique_customers',
            'order_total_price': 'avg_price',
            'hour': 'popular_hour',
            'is_weekend': 'weekend_popularity'
        })
        
        total_orders = self.df['order_id'].nunique()
        item_features['popularity_score'] = item_features['total_orders'] / total_orders
        
        item_features['repeat_purchase_rate'] = (
            self.df.groupby('product_full').apply(
                lambda x: (x.groupby('customer_id').size() > 1).sum() / x['customer_id'].nunique()
            )
        )
        
        self.item_features = item_features
        
        self.logger.info(f"Created {len(item_features.columns)} item features")
        
        return self
    
    def create_order_level_sequences(self, sequence_length: int = 5, min_orders: int = 3) -> 'OrderLevelFeatureEngineering':
        self.logger.info("="*80)
        self.logger.info(f"CREATING ORDER-LEVEL SEQUENCES (sequence_length={sequence_length})")
        self.logger.info("="*80)
        self.logger.info("Each sequence represents ORDERS (visits), not individual items")
        
        sequences = []
        
        item_to_id = {item: idx for idx, item in enumerate(self.user_item_matrix.columns)}
        n_items = len(item_to_id)
        
        for customer_id in self.df['customer_id'].unique():
            customer_data = self.df[self.df['customer_id'] == customer_id].sort_values('order_datetime')
            
            customer_orders = customer_data.groupby('order_id').agg({
                'product_full': lambda x: list(x),
                'order_datetime': 'first',
                'hour': 'first',
                'day_of_week': 'first',
                'is_weekend': 'first',
                'order_total_price': 'first'
            }).sort_values('order_datetime')
            
            if len(customer_orders) < min_orders + 1:
                continue
            
            for i in range(sequence_length, len(customer_orders)):
                previous_orders = customer_orders.iloc[i-sequence_length:i]
                target_order = customer_orders.iloc[i]
                
                order_sequences = []
                for _, order in previous_orders.iterrows():
                    order_vector = np.zeros(n_items, dtype=np.float32)
                    for item in order['product_full']:
                        item_id = item_to_id.get(item, 0)
                        order_vector[item_id] = 1
                    order_sequences.append(order_vector)
                
                order_sequence_matrix = np.array(order_sequences)
                
                target_items = target_order['product_full']
                for target_item in target_items:
                    target_item_id = item_to_id.get(target_item, 0)
                    
                    sequences.append({
                        'customer_id': customer_id,
                        'order_sequence': order_sequence_matrix,
                        'target_item_id': target_item_id,
                        'target_item': target_item,
                        'target_order_items': target_items,
                        'n_previous_orders': len(previous_orders),
                        'hour': target_order['hour'],
                        'day_of_week': target_order['day_of_week'],
                        'is_weekend': target_order['is_weekend'],
                        'timestamp': target_order['order_datetime'],
                        'order_value': target_order['order_total_price']
                    })
        
        self.sequential_data = pd.DataFrame(sequences)
        
        self.logger.info(f"Created {len(self.sequential_data)} training samples")
        self.logger.info(f"Each sample: {sequence_length} previous orders -> 1 target item")
        self.logger.info(f"Unique customers: {self.sequential_data['customer_id'].nunique()}")
        self.logger.info(f"Unique target items: {self.sequential_data['target_item_id'].nunique()}")
        
        sample = self.sequential_data.iloc[0]
        self.logger.info(f"\nExample sequence shape: {sample['order_sequence'].shape}")
        self.logger.info(f"  (sequence_length={sequence_length}, n_items={n_items})")
        self.logger.info(f"Example target order: {sample['target_order_items']}")
        
        return self
    
    def create_basket_level_sequences(self, sequence_length: int = 5, min_orders: int = 3) -> 'OrderLevelFeatureEngineering':
        self.logger.info("="*80)
        self.logger.info(f"CREATING BASKET-LEVEL SEQUENCES (ALTERNATIVE APPROACH)")
        self.logger.info("="*80)
        self.logger.info("Predicts entire next basket based on previous baskets")
        
        sequences = []
        
        item_to_id = {item: idx for idx, item in enumerate(self.user_item_matrix.columns)}
        n_items = len(item_to_id)
        
        for customer_id in self.df['customer_id'].unique():
            customer_data = self.df[self.df['customer_id'] == customer_id].sort_values('order_datetime')
            
            customer_orders = customer_data.groupby('order_id').agg({
                'product_full': lambda x: list(x),
                'order_datetime': 'first',
                'hour': 'first',
                'day_of_week': 'first',
                'is_weekend': 'first',
                'order_total_price': 'first'
            }).sort_values('order_datetime')
            
            if len(customer_orders) < min_orders + 1:
                continue
            
            for i in range(sequence_length, len(customer_orders)):
                previous_orders = customer_orders.iloc[i-sequence_length:i]
                target_order = customer_orders.iloc[i]
                
                order_sequences = []
                for _, order in previous_orders.iterrows():
                    order_vector = np.zeros(n_items, dtype=np.float32)
                    for item in order['product_full']:
                        item_id = item_to_id.get(item, 0)
                        order_vector[item_id] = 1
                    order_sequences.append(order_vector)
                
                order_sequence_matrix = np.array(order_sequences)
                
                target_basket = np.zeros(n_items, dtype=np.float32)
                for item in target_order['product_full']:
                    item_id = item_to_id.get(item, 0)
                    target_basket[item_id] = 1
                
                sequences.append({
                    'customer_id': customer_id,
                    'order_sequence': order_sequence_matrix,
                    'target_basket': target_basket,
                    'target_items': target_order['product_full'],
                    'n_previous_orders': len(previous_orders),
                    'hour': target_order['hour'],
                    'day_of_week': target_order['day_of_week'],
                    'is_weekend': target_order['is_weekend'],
                    'timestamp': target_order['order_datetime'],
                    'order_value': target_order['order_total_price']
                })
        
        self.basket_sequential_data = pd.DataFrame(sequences)
        
        self.logger.info(f"Created {len(self.basket_sequential_data)} basket prediction samples")
        self.logger.info(f"Each sample: {sequence_length} previous baskets -> 1 target basket")
        self.logger.info(f"Unique customers: {self.basket_sequential_data['customer_id'].nunique()}")
        
        return self
    
    def temporal_train_val_test_split(self, 
                                       train_ratio: float = 0.7, 
                                       val_ratio: float = 0.15,
                                       use_basket_mode: bool = False) -> 'OrderLevelFeatureEngineering':
        self.logger.info("="*80)
        self.logger.info("CREATING TEMPORAL TRAIN/VAL/TEST SPLIT")
        self.logger.info("="*80)
        
        data_to_split = self.basket_sequential_data if use_basket_mode else self.sequential_data
        
        data_to_split = data_to_split.sort_values('timestamp')
        
        n = len(data_to_split)
        train_end = int(n * train_ratio)
        val_end = int(n * (train_ratio + val_ratio))
        
        self.train_data = data_to_split.iloc[:train_end].reset_index(drop=True)
        self.val_data = data_to_split.iloc[train_end:val_end].reset_index(drop=True)
        self.test_data = data_to_split.iloc[val_end:].reset_index(drop=True)
        
        self.logger.info(f"Train set: {len(self.train_data)} ({len(self.train_data)/n*100:.1f}%)")
        self.logger.info(f"Val set: {len(self.val_data)} ({len(self.val_data)/n*100:.1f}%)")
        self.logger.info(f"Test set: {len(self.test_data)} ({len(self.test_data)/n*100:.1f}%)")
        
        self.logger.info(f"\nTrain date range: {self.train_data['timestamp'].min()} to {self.train_data['timestamp'].max()}")
        self.logger.info(f"Val date range: {self.val_data['timestamp'].min()} to {self.val_data['timestamp'].max()}")
        self.logger.info(f"Test date range: {self.test_data['timestamp'].min()} to {self.test_data['timestamp'].max()}")
        
        return self
    
    def prepare_arrays_for_item_prediction(self) -> 'OrderLevelFeatureEngineering':
        self.logger.info("="*80)
        self.logger.info("PREPARING ARRAYS FOR ITEM-LEVEL PREDICTION")
        self.logger.info("="*80)
        
        def to_arrays(data):
            X_seq = np.array([seq for seq in data['order_sequence'].values])
            X_context = data[['hour', 'day_of_week', 'is_weekend']].values
            y = data['target_item_id'].values
            customers = data['customer_id'].values
            return X_seq, X_context, y, customers
        
        self.X_train_seq, self.X_train_context, self.y_train, self.customers_train = to_arrays(self.train_data)
        self.X_val_seq, self.X_val_context, self.y_val, self.customers_val = to_arrays(self.val_data)
        self.X_test_seq, self.X_test_context, self.y_test, self.customers_test = to_arrays(self.test_data)
        
        self.logger.info(f"X_train_seq shape: {self.X_train_seq.shape}")
        self.logger.info(f"  (n_samples, sequence_length, n_items)")
        self.logger.info(f"X_train_context shape: {self.X_train_context.shape}")
        self.logger.info(f"y_train shape: {self.y_train.shape}")
        
        return self
    
    def prepare_arrays_for_basket_prediction(self) -> 'OrderLevelFeatureEngineering':
        self.logger.info("="*80)
        self.logger.info("PREPARING ARRAYS FOR BASKET-LEVEL PREDICTION")
        self.logger.info("="*80)
        
        def to_arrays(data):
            X_seq = np.array([seq for seq in data['order_sequence'].values])
            X_context = data[['hour', 'day_of_week', 'is_weekend']].values
            y_basket = np.array([basket for basket in data['target_basket'].values])
            customers = data['customer_id'].values
            return X_seq, X_context, y_basket, customers
        
        self.X_train_seq, self.X_train_context, self.y_train_basket, self.customers_train = to_arrays(self.train_data)
        self.X_val_seq, self.X_val_context, self.y_val_basket, self.customers_val = to_arrays(self.val_data)
        self.X_test_seq, self.X_test_context, self.y_test_basket, self.customers_test = to_arrays(self.test_data)
        
        self.logger.info(f"X_train_seq shape: {self.X_train_seq.shape}")
        self.logger.info(f"  (n_samples, sequence_length, n_items)")
        self.logger.info(f"y_train_basket shape: {self.y_train_basket.shape}")
        self.logger.info(f"  (n_samples, n_items) - multi-label classification")
        
        return self
    
    def get_feature_metadata(self) -> Dict:
        metadata = {
            'n_users': len(self.user_item_matrix.index),
            'n_items': len(self.user_item_matrix.columns),
            'sequence_length': self.X_train_seq.shape[1] if hasattr(self, 'X_train_seq') else 0,
            'n_context_features': self.X_train_context.shape[1] if hasattr(self, 'X_train_context') else 0,
            'item_to_id': {item: idx for idx, item in enumerate(self.user_item_matrix.columns)},
            'id_to_item': {idx: item for idx, item in enumerate(self.user_item_matrix.columns)}
        }
        return metadata
    
    def run_feature_engineering(self, 
                                sequence_length: int = 5,
                                prediction_mode: str = 'item') -> Tuple[Dict, Dict]:
        self.logger.info("="*80)
        self.logger.info("STEP 3: ORDER-LEVEL FEATURE ENGINEERING")
        self.logger.info("="*80)
        self.logger.info(f"Prediction mode: {prediction_mode}")
        self.logger.info(f"  'item' = Predict next items one-by-one")
        self.logger.info(f"  'basket' = Predict entire next order basket")
        
        self.create_user_item_matrix()
        self.create_user_features()
        self.create_item_features()
        
        if prediction_mode == 'basket':
            self.create_basket_level_sequences(sequence_length=sequence_length)
            self.temporal_train_val_test_split(use_basket_mode=True)
            self.prepare_arrays_for_basket_prediction()
        else:
            self.create_order_level_sequences(sequence_length=sequence_length)
            self.temporal_train_val_test_split(use_basket_mode=False)
            self.prepare_arrays_for_item_prediction()
        
        metadata = self.get_feature_metadata()
        
        arrays = {
            'X_train_seq': self.X_train_seq,
            'X_train_context': self.X_train_context,
            'y_train': getattr(self, 'y_train_basket', None) or self.y_train,
            'X_val_seq': self.X_val_seq,
            'X_val_context': self.X_val_context,
            'y_val': getattr(self, 'y_val_basket', None) or self.y_val,
            'X_test_seq': self.X_test_seq,
            'X_test_context': self.X_test_context,
            'y_test': getattr(self, 'y_test_basket', None) or self.y_test,
            'prediction_mode': prediction_mode
        }
        
        self.logger.info("="*80)
        self.logger.info("STEP 3 COMPLETE")
        self.logger.info("="*80)
        self.logger.info("Order-level sequences ready for model training")
        
        return arrays, metadata


if __name__ == "__main__":
    logger.info("CORRECTED STEP 3: Order-Level Sequential Feature Engineering")
    logger.info("")
    logger.info("Key Differences from Previous Version:")
    logger.info("  1. Each sequence element is an ORDER (visit), not an item")
    logger.info("  2. Sequences represent: [Order1, Order2, Order3] -> Order4")
    logger.info("  3. Two prediction modes:")
    logger.info("     - 'item': Predict items in next order one-by-one")
    logger.info("     - 'basket': Predict entire next order as multi-label")
    logger.info("")
    logger.info("Usage:")
    logger.info("  fe = OrderLevelFeatureEngineering(clean_df)")
    logger.info("  arrays, metadata = fe.run_feature_engineering(sequence_length=5, prediction_mode='item')")

2025-11-23 19:45:09,222 - __main__ - INFO - CORRECTED STEP 3: Order-Level Sequential Feature Engineering
2025-11-23 19:45:09,222 - __main__ - INFO -
2025-11-23 19:45:09,228 - __main__ - INFO - Key Differences from Previous Version:
2025-11-23 19:45:09,228 - __main__ - INFO -   1. Each sequence element is an ORDER (visit), not an item
2025-11-23 19:45:09,228 - __main__ - INFO -   2. Sequences represent: [Order1, Order2, Order3] -> Order4
2025-11-23 19:45:09,228 - __main__ - INFO -   3. Two prediction modes:
2025-11-23 19:45:09,228 - __main__ - INFO -      - 'item': Predict items in next order one-by-one
2025-11-23 19:45:09,228 - __main__ - INFO -      - 'basket': Predict entire next order as multi-label
2025-11-23 19:45:09,231 - __main__ - INFO -
2025-11-23 19:45:09,231 - __main__ - INFO - Usage:
2025-11-23 19:45:09,231 - __main__ - INFO -   fe = OrderLevelFeatureEngineering(clean_df)
2025-11-23 19:45:09,231 - __main__ - INFO -   arrays, metadata = fe.run_feature_engineering(sequence_length=5, prediction_mode='item')

In [73]:
fe = OrderLevelFeatureEngineering(clean_df)

2025-11-23 19:45:40,172 - __main__ - INFO - Order-Level Feature Engineering initialized

In [ ]:
fe = OrderLevelFeatureEngineering(clean_df)
arrays, metadata = fe.run_feature_engineering(sequence_length=5, prediction_mode='item')

2025-11-23 19:45:46,973 - __main__ - INFO - ================================================================================
2025-11-23 19:45:46,974 - __main__ - INFO - STEP 3: ORDER-LEVEL FEATURE ENGINEERING
2025-11-23 19:45:46,975 - __main__ - INFO - ================================================================================
2025-11-23 19:45:46,976 - __main__ - INFO - Prediction mode: item
2025-11-23 19:45:46,976 - __main__ - INFO -   'item' = Predict next items one-by-one
2025-11-23 19:45:46,976 - __main__ - INFO -   'basket' = Predict entire next order basket
2025-11-23 19:45:46,996 - __main__ - INFO - Matrix shape: (1706, 255)
2025-11-23 19:45:46,997 - __main__ - INFO - Sparsity: 97.92%
2025-11-23 19:45:46,997 - __main__ - INFO - ================================================================================
2025-11-23 19:45:46,998 - __main__ - INFO - CREATING USER FEATURES
2025-11-23 19:45:46,998 - __main__ - INFO - ================================================================================
2025-11-23 19:45:47,298 - __main__ - INFO - Created 19 user features
2025-11-23 19:45:47,299 - __main__ - INFO - ================================================================================
2025-11-23 19:45:47,299 - __main__ - INFO - CREATING ITEM FEATURES
2025-11-23 19:45:47,300 - __main__ - INFO - ================================================================================
2025-11-23 19:45:47,413 - __main__ - INFO - Created 10 item features
2025-11-23 19:45:47,413 - __main__ - INFO - ================================================================================
2025-11-23 19:45:47,413 - __main__ - INFO - CREATING ORDER-LEVEL SEQUENCES (sequence_length=5)
2025-11-23 19:45:47,413 - __main__ - INFO - ================================================================================
2025-11-23 19:45:47,413 - __main__ - INFO - Each sequence represents ORDERS (visits), not individual items
2025-11-23 19:45:56,564 - __main__ - INFO - Created 59896 training samples
2025-11-23 19:45:56,564 - __main__ - INFO - Each sample: 5 previous orders -> 1 target item
2025-11-23 19:45:56,564 - __main__ - INFO - Unique customers: 470
2025-11-23 19:45:56,564 - __main__ - INFO - Unique target items: 237
2025-11-23 19:45:56,564 - __main__ - INFO -
Example sequence shape: (5, 255)
2025-11-23 19:45:56,564 - __main__ - INFO -   (sequence_length=5, n_items=255)
2025-11-23 19:45:56,564 - __main__ - INFO - Example target order: ['Freshly Squeezed Juice_Regular', 'Muffin_Raspberry and White Chocolate', 'Iced Chocolate with Cream_Regular', 'Toasted Roll_Chicken Schnitzel w/ Cheese and Lettuce', 'Cappuccino_Regular']
2025-11-23 19:45:56,577 - __main__ - INFO - ================================================================================
2025-11-23 19:45:56,577 - __main__ - INFO - CREATING TEMPORAL TRAIN/VAL/TEST SPLIT
2025-11-23 19:45:56,577 - __main__ - INFO - ================================================================================
2025-11-23 19:45:56,592 - __main__ - INFO - Train set: 41927 (70.0%)
2025-11-23 19:45:56,593 - __main__ - INFO - Val set: 8984 (15.0%)
2025-11-23 19:45:56,594 - __main__ - INFO - Test set: 8985 (15.0%)
2025-11-23 19:45:56,594 - __main__ - INFO -
Train date range: 2019-05-27 16:01:12 to 2023-01-25 07:26:47
2025-11-23 19:45:56,594 - __main__ - INFO - Val date range: 2023-01-25 07:32:46 to 2023-08-10 08:31:19
2025-11-23 19:45:56,594 - __main__ - INFO - Test date range: 2023-08-10 08:47:07 to 2024-03-06 11:53:26
2025-11-23 19:45:56,594 - __main__ - INFO - ================================================================================
2025-11-23 19:45:56,594 - __main__ - INFO - PREPARING ARRAYS FOR ITEM-LEVEL PREDICTION
2025-11-23 19:45:56,594 - __main__ - INFO - ================================================================================
2025-11-23 19:45:56,694 - __main__ - INFO - X_train_seq shape: (41927, 5, 255)
2025-11-23 19:45:56,694 - __main__ - INFO -   (n_samples, sequence_length, n_items)
2025-11-23 19:45:56,694 - __main__ - INFO - X_train_context shape: (41927, 3)
2025-11-23 19:45:56,694 - __main__ - INFO - y_train shape: (41927,)
2025-11-23 19:45:56,694 - __main__ - INFO - ================================================================================
2025-11-23 19:45:56,697 - __main__ - INFO - STEP 3 COMPLETE
2025-11-23 19:45:56,697 - __main__ - INFO - ================================================================================
2025-11-23 19:45:56,697 - __main__ - INFO - Order-level sequences ready for model training

In [78]:
import pandas as pd
import numpy as np
import logging
from datetime import timedelta
from sklearn.cluster import KMeans

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class OrderAwareAugmentation:
    
    def __init__(self, df: pd.DataFrame):
        self.df = df.copy()
        self.logger = logger
        self.original_size = len(df)
        
    def augment_order_temporal_jitter(self, jitter_hours: int = 2, probability: float = 0.3) -> pd.DataFrame:
        self.logger.info("="*80)
        self.logger.info("AUGMENTATION 1: ORDER-LEVEL TEMPORAL JITTERING")
        self.logger.info("="*80)
        self.logger.info("Shifts entire orders in time while maintaining item relationships")
        
        orders = self.df.groupby('order_id')
        eligible_orders = list(orders.groups.keys())
        
        n_to_jitter = int(len(eligible_orders) * probability)
        orders_to_jitter = np.random.choice(eligible_orders, size=n_to_jitter, replace=False)
        
        augmented_records = []
        for order_id in orders_to_jitter:
            order_data = self.df[self.df['order_id'] == order_id].copy()
            
            jitter_minutes = np.random.randint(-jitter_hours*60, jitter_hours*60)
            order_data['order_datetime'] = order_data['order_datetime'] + pd.to_timedelta(jitter_minutes, unit='m')
            
            order_data['order_date'] = order_data['order_datetime'].dt.date.astype(str)
            order_data['order_time'] = order_data['order_datetime'].dt.time.astype(str)
            order_data['hour'] = order_data['order_datetime'].dt.hour
            order_data['day_of_week'] = order_data['order_datetime'].dt.dayofweek
            order_data['is_weekend'] = order_data['day_of_week'].isin([5, 6]).astype(int)
            
            order_data['order_id'] = order_data['order_id'] + 10000000
            order_data['order_item_id'] = order_data['order_item_id'] + 10000000
            
            augmented_records.append(order_data)
        
        if augmented_records:
            result = pd.concat(augmented_records, ignore_index=True)
            self.logger.info(f"Generated {len(result)} records from {n_to_jitter} jittered orders")
            return result
        else:
            return pd.DataFrame()
    
    def augment_basket_item_swap(self, probability: float = 0.2) -> pd.DataFrame:
        self.logger.info("="*80)
        self.logger.info("AUGMENTATION 2: WITHIN-BASKET ITEM SWAP")
        self.logger.info("="*80)
        self.logger.info("Swaps items within same order while preserving order structure")
        
        variant_groups = self.df.groupby('product_name')['product_variant'].unique().to_dict()
        variant_groups = {k: v for k, v in variant_groups.items() if len(v) > 1}
        
        orders = self.df.groupby('order_id')
        eligible_orders = [
            order_id for order_id, group in orders 
            if any(group['product_name'].isin(variant_groups.keys()))
        ]
        
        n_to_augment = int(len(eligible_orders) * probability)
        orders_to_augment = np.random.choice(eligible_orders, size=n_to_augment, replace=False)
        
        augmented_records = []
        for order_id in orders_to_augment:
            order_data = self.df[self.df['order_id'] == order_id].copy()
            
            for idx in order_data.index:
                product_name = order_data.loc[idx, 'product_name']
                if product_name in variant_groups and np.random.random() < 0.5:
                    current_variant = order_data.loc[idx, 'product_variant']
                    possible_variants = variant_groups[product_name]
                    other_variants = [v for v in possible_variants if v != current_variant]
                    
                    if len(other_variants) > 0:
                        new_variant = np.random.choice(other_variants)
                        order_data.loc[idx, 'product_variant'] = new_variant
                        order_data.loc[idx, 'product_full'] = f"{product_name}_{new_variant}"
            
            order_data['order_id'] = order_data['order_id'] + 20000000
            order_data['order_item_id'] = order_data['order_item_id'] + 20000000
            
            augmented_records.append(order_data)
        
        if augmented_records:
            result = pd.concat(augmented_records, ignore_index=True)
            self.logger.info(f"Generated {len(result)} records from {n_to_augment} augmented orders")
            return result
        else:
            return pd.DataFrame()
    
    def augment_basket_item_addition(self, probability: float = 0.15) -> pd.DataFrame:
        self.logger.info("="*80)
        self.logger.info("AUGMENTATION 3: BASKET ITEM ADDITION")
        self.logger.info("="*80)
        self.logger.info("Adds frequently co-occurring items to existing orders")
        
        item_cooccurrence = {}
        for order_id, group in self.df.groupby('order_id'):
            items = group['product_full'].tolist()
            for i, item1 in enumerate(items):
                for item2 in items[i+1:]:
                    key = tuple(sorted([item1, item2]))
                    item_cooccurrence[key] = item_cooccurrence.get(key, 0) + 1
        
        orders = list(self.df.groupby('order_id'))
        n_to_augment = int(len(orders) * probability)
        orders_to_augment = np.random.choice(len(orders), size=n_to_augment, replace=False)
        
        augmented_records = []
        for idx in orders_to_augment:
            order_id, order_data = orders[idx]
            order_data = order_data.copy()
            
            existing_items = set(order_data['product_full'].tolist())
            
            candidate_items = {}
            for item in existing_items:
                for (item1, item2), count in item_cooccurrence.items():
                    if item == item1 and item2 not in existing_items:
                        candidate_items[item2] = candidate_items.get(item2, 0) + count
                    elif item == item2 and item1 not in existing_items:
                        candidate_items[item1] = candidate_items.get(item1, 0) + count
            
            if candidate_items:
                new_item = max(candidate_items.items(), key=lambda x: x[1])[0]
                
                item_info = self.df[self.df['product_full'] == new_item].iloc[0]
                
                new_row = order_data.iloc[0].copy()
                new_row['product_full'] = new_item
                new_row['product_name'] = item_info['product_name']
                new_row['product_variant'] = item_info['product_variant']
                new_row['product_category'] = item_info['product_category']
                new_row['order_item_id'] = order_data['order_item_id'].max() + 1
                
                order_data = pd.concat([order_data, pd.DataFrame([new_row])], ignore_index=True)
            
            order_data['order_id'] = order_data['order_id'] + 30000000
            order_data['order_item_id'] = order_data['order_item_id'] + 30000000
            
            augmented_records.append(order_data)
        
        if augmented_records:
            result = pd.concat(augmented_records, ignore_index=True)
            self.logger.info(f"Generated {len(result)} records from {n_to_augment} augmented orders")
            return result
        else:
            return pd.DataFrame()
    
    def augment_synthetic_orders(self, n_synthetic: int = 200) -> pd.DataFrame:
        self.logger.info("="*80)
        self.logger.info("AUGMENTATION 4: SYNTHETIC ORDER GENERATION")
        self.logger.info("="*80)
        self.logger.info("Creates synthetic orders based on customer clusters")
        
        customer_order_patterns = self.df.groupby('customer_id').apply(
            lambda x: x.groupby('order_id')['product_full'].apply(list).tolist()
        ).to_dict()
        
        customers = list(customer_order_patterns.keys())
        n_clusters = min(10, len(customers))
        
        customer_features = []
        for customer_id in customers:
            orders = customer_order_patterns[customer_id]
            avg_basket_size = np.mean([len(order) for order in orders])
            unique_items = len(set([item for order in orders for item in order]))
            customer_features.append([avg_basket_size, unique_items])
        
        kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
        clusters = kmeans.fit_predict(customer_features)
        
        customer_clusters = {}
        for customer_id, cluster in zip(customers, clusters):
            if cluster not in customer_clusters:
                customer_clusters[cluster] = []
            customer_clusters[cluster].append(customer_id)
        
        augmented_records = []
        
        for i in range(n_synthetic):
            cluster = np.random.randint(0, n_clusters)
            if cluster not in customer_clusters:
                continue
            
            template_customer = np.random.choice(customer_clusters[cluster])
            customer_orders = self.df[self.df['customer_id'] == template_customer]
            
            template_order_id = np.random.choice(customer_orders['order_id'].unique())
            template_order = customer_orders[customer_orders['order_id'] == template_order_id].copy()
            
            synthetic_customer_id = 900000 + i
            synthetic_order_id = 40000000 + i
            
            template_order['customer_id'] = synthetic_customer_id
            template_order['order_id'] = synthetic_order_id
            template_order['order_item_id'] = template_order['order_item_id'] + synthetic_order_id
            
            augmented_records.append(template_order)
        
        if augmented_records:
            result = pd.concat(augmented_records, ignore_index=True)
            self.logger.info(f"Generated {len(result)} records from {n_synthetic} synthetic orders")
            return result
        else:
            return pd.DataFrame()
    
    def run_augmentation(self, target_multiplier: float = 1.5) -> pd.DataFrame:
        self.logger.info("="*80)
        self.logger.info("STEP 4: ORDER-AWARE DATA AUGMENTATION")
        self.logger.info("="*80)
        self.logger.info(f"Original dataset size: {self.original_size:,}")
        self.logger.info(f"Target size: {int(self.original_size * target_multiplier):,}")
        
        augmented_datasets = [self.df]
        
        aug1 = self.augment_order_temporal_jitter(jitter_hours=2, probability=0.3)
        if len(aug1) > 0:
            augmented_datasets.append(aug1)
        
        aug2 = self.augment_basket_item_swap(probability=0.2)
        if len(aug2) > 0:
            augmented_datasets.append(aug2)
        
        aug3 = self.augment_basket_item_addition(probability=0.15)
        if len(aug3) > 0:
            augmented_datasets.append(aug3)
        
        current_size = sum(len(d) for d in augmented_datasets)
        remaining = max(0, int(self.original_size * target_multiplier) - current_size)
        
        if remaining > 0:
            avg_items_per_order = self.original_size / self.df['order_id'].nunique()
            n_synthetic = max(10, int(remaining / avg_items_per_order))
            aug4 = self.augment_synthetic_orders(n_synthetic=n_synthetic)
            if len(aug4) > 0:
                augmented_datasets.append(aug4)
        
        final_df = pd.concat(augmented_datasets, ignore_index=True)
        
        final_df = final_df.drop_duplicates(
            subset=['customer_id', 'order_id', 'product_full'],
            keep='first'
        )
        
        self.logger.info("="*80)
        self.logger.info("AUGMENTATION COMPLETE")
        self.logger.info("="*80)
        self.logger.info(f"Final dataset size: {len(final_df):,}")
        self.logger.info(f"Size increase: {((len(final_df) / self.original_size) - 1) * 100:.1f}%")
        self.logger.info(f"Unique customers: {final_df['customer_id'].nunique():,}")
        self.logger.info(f"Unique orders: {final_df['order_id'].nunique():,}")
        self.logger.info(f"Average items per order: {len(final_df) / final_df['order_id'].nunique():.2f}")
        
        self.logger.info("="*80)
        self.logger.info("STEP 4 COMPLETE")
        self.logger.info("="*80)
        
        return final_df


if __name__ == "__main__":
    logger.info("UPDATED STEP 4: Order-Aware Data Augmentation")
    logger.info("Usage: aug = OrderAwareAugmentation(clean_df)")
    logger.info("       augmented_df = aug.run_augmentation(target_multiplier=1.5)")

2025-11-23 19:59:16,057 - __main__ - INFO - UPDATED STEP 4: Order-Aware Data Augmentation
2025-11-23 19:59:16,057 - __main__ - INFO - Usage: aug = OrderAwareAugmentation(clean_df)
2025-11-23 19:59:16,057 - __main__ - INFO -        augmented_df = aug.run_augmentation(target_multiplier=1.5)

In [79]:
aug = OrderAwareAugmentation(clean_df)
augmented_df = aug.run_augmentation(target_multiplier=1.5)

2025-11-23 19:59:17,064 - __main__ - INFO - ================================================================================
2025-11-23 19:59:17,065 - __main__ - INFO - STEP 4: ORDER-AWARE DATA AUGMENTATION
2025-11-23 19:59:17,065 - __main__ - INFO - ================================================================================
2025-11-23 19:59:17,066 - __main__ - INFO - Original dataset size: 70,514
2025-11-23 19:59:17,066 - __main__ - INFO - Target size: 105,771
2025-11-23 19:59:17,067 - __main__ - INFO - ================================================================================
2025-11-23 19:59:17,067 - __main__ - INFO - AUGMENTATION 1: ORDER-LEVEL TEMPORAL JITTERING
2025-11-23 19:59:17,068 - __main__ - INFO - ================================================================================
2025-11-23 19:59:17,068 - __main__ - INFO - Shifts entire orders in time while maintaining item relationships
2025-11-23 19:59:32,900 - __main__ - INFO - Generated 21190 records from 10952 jittered orders
2025-11-23 19:59:33,016 - __main__ - INFO - ================================================================================
2025-11-23 19:59:33,016 - __main__ - INFO - AUGMENTATION 2: WITHIN-BASKET ITEM SWAP
2025-11-23 19:59:33,016 - __main__ - INFO - ================================================================================
2025-11-23 19:59:33,016 - __main__ - INFO - Swaps items within same order while preserving order structure
2025-11-23 19:59:42,041 - __main__ - INFO - Generated 13639 records from 7120 augmented orders
2025-11-23 19:59:42,083 - __main__ - INFO - ================================================================================
2025-11-23 19:59:42,083 - __main__ - INFO - AUGMENTATION 3: BASKET ITEM ADDITION
2025-11-23 19:59:42,083 - __main__ - INFO - ================================================================================
2025-11-23 19:59:42,083 - __main__ - INFO - Adds frequently co-occurring items to existing orders
2025-11-23 20:00:15,718 - __main__ - INFO - Generated 15987 records from 5476 augmented orders
2025-11-23 20:00:16,427 - __main__ - INFO - ================================================================================
2025-11-23 20:00:16,428 - __main__ - INFO - AUGMENTATION COMPLETE
2025-11-23 20:00:16,429 - __main__ - INFO - ================================================================================
2025-11-23 20:00:16,429 - __main__ - INFO - Final dataset size: 110,469
2025-11-23 20:00:16,430 - __main__ - INFO - Size increase: 56.7%
2025-11-23 20:00:16,431 - __main__ - INFO - Unique customers: 1,706
2025-11-23 20:00:16,434 - __main__ - INFO - Unique orders: 60,056
2025-11-23 20:00:16,436 - __main__ - INFO - Average items per order: 1.84
2025-11-23 20:00:16,437 - __main__ - INFO - ================================================================================
2025-11-23 20:00:16,437 - __main__ - INFO - STEP 4 COMPLETE
2025-11-23 20:00:16,437 - __main__ - INFO - ================================================================================

In [80]:
augmented_df

,order_id,order_item_id,order_date,order_time,order_total_price,order_gst,cart_order_time,product_name,product_variant,product_category,...,total_orders,total_lifetime_value,customer_segment,product_full,order_datetime,hour,day_of_week,month,year,is_weekend
0,3318,2,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Croissant,Plain,Kitchen,...,95,172163,VIP,Croissant_Plain,2019-05-26 13:17:13,13,6,5,2019,1
1,3318,1,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Cappuccino,Regular,Hot Drinks,...,95,172163,VIP,Cappuccino_Regular,2019-05-26 13:17:13,13,6,5,2019,1
2,3318,3,2019-05-26,13:17:13,12.5,1.140000000,ASAP,Iced Coffee with Cream,Regular,Cold Drinks,...,95,172163,VIP,Iced Coffee with Cream_Regular,2019-05-26 13:17:13,13,6,5,2019,1
3,3319,1,2019-05-26,21:47:03,14.0,1.270000000,1558903500,Croissant,Bacon and Egg,Kitchen,...,95,172163,VIP,Croissant_Bacon and Egg,2019-05-26 21:47:03,21,6,5,2019,1
4,3319,2,2019-05-26,21:47:03,14.0,1.270000000,1558903500,Freshly Squeezed Juice,Regular,Cold Drinks,...,95,172163,VIP,Freshly Squeezed Juice_Regular,2019-05-26 21:47:03,21,6,5,2019,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121324,30036643,30000002,2023-10-15,08:38:45,16.1,1.460000000,ASAP,Latte,Large,Hot Drinks,...,714,690300,VIP,Latte_Large,2023-10-15 08:38:45,8,6,10,2023,1
121326,30036643,30000001,2023-10-15,08:38:45,16.1,1.460000000,ASAP,Chai Latte,Large,Hot Drinks,...,714,690300,VIP,Chai Latte_Large,2023-10-15 08:38:45,8,6,10,2023,1
121327,30036643,30000004,2023-10-15,08:38:45,16.1,1.460000000,ASAP,Cappuccino,Large,Hot Drinks,...,714,690300,VIP,Cappuccino_Large,2023-10-15 08:38:45,8,6,10,2023,1
121328,30007604,30000001,2020-09-30,07:30:49,4.3,0.390000000,ASAP,Cappuccino,Large,Hot Drinks,...,714,690300,VIP,Cappuccino_Large,2020-09-30 07:30:49,7,2,9,2020,0
121329,30007604,30000002,2020-09-30,07:30:49,4.3,0.390000000,ASAP,Latte,Large,Hot Drinks,...,714,690300,VIP,Latte_Large,2020-09-30 07:30:49,7,2,9,2020,0

In [81]:
fe = OrderLevelFeatureEngineering(augmented_df)
arrays, metadata = fe.run_feature_engineering(sequence_length=5, prediction_mode='item')

2025-11-23 20:00:42,708 - __main__ - INFO - Order-Level Feature Engineering initialized
2025-11-23 20:00:42,739 - __main__ - INFO - ================================================================================
2025-11-23 20:00:42,739 - __main__ - INFO - STEP 3: ORDER-LEVEL FEATURE ENGINEERING
2025-11-23 20:00:42,740 - __main__ - INFO - ================================================================================
2025-11-23 20:00:42,740 - __main__ - INFO - Prediction mode: item
2025-11-23 20:00:42,740 - __main__ - INFO -   'item' = Predict next items one-by-one
2025-11-23 20:00:42,741 - __main__ - INFO -   'basket' = Predict entire next order basket
2025-11-23 20:00:42,760 - __main__ - INFO - Matrix shape: (1706, 255)
2025-11-23 20:00:42,760 - __main__ - INFO - Sparsity: 97.43%
2025-11-23 20:00:42,760 - __main__ - INFO - ================================================================================
2025-11-23 20:00:42,760 - __main__ - INFO - CREATING USER FEATURES
2025-11-23 20:00:42,760 - __main__ - INFO - ================================================================================
2025-11-23 20:00:43,010 - __main__ - INFO - Created 19 user features
2025-11-23 20:00:43,010 - __main__ - INFO - ================================================================================
2025-11-23 20:00:43,011 - __main__ - INFO - CREATING ITEM FEATURES
2025-11-23 20:00:43,011 - __main__ - INFO - ================================================================================
2025-11-23 20:00:43,148 - __main__ - INFO - Created 10 item features
2025-11-23 20:00:43,148 - __main__ - INFO - ================================================================================
2025-11-23 20:00:43,155 - __main__ - INFO - CREATING ORDER-LEVEL SEQUENCES (sequence_length=5)
2025-11-23 20:00:43,155 - __main__ - INFO - ================================================================================
2025-11-23 20:00:43,155 - __main__ - INFO - Each sequence represents ORDERS (visits), not individual items
2025-11-23 20:00:57,016 - __main__ - INFO - Created 98687 training samples
2025-11-23 20:00:57,016 - __main__ - INFO - Each sample: 5 previous orders -> 1 target item
2025-11-23 20:00:57,018 - __main__ - INFO - Unique customers: 612
2025-11-23 20:00:57,019 - __main__ - INFO - Unique target items: 245
2025-11-23 20:00:57,019 - __main__ - INFO -
Example sequence shape: (5, 255)
2025-11-23 20:00:57,020 - __main__ - INFO -   (sequence_length=5, n_items=255)
2025-11-23 20:00:57,020 - __main__ - INFO - Example target order: ['Toasted Roll_Chicken Schnitzel w/ Cheese and Lettuce', 'Iced Chocolate with Cream_Regular', 'White Hot Chocolate_Extra Large']
2025-11-23 20:00:57,034 - __main__ - INFO - ================================================================================
2025-11-23 20:00:57,034 - __main__ - INFO - CREATING TEMPORAL TRAIN/VAL/TEST SPLIT
2025-11-23 20:00:57,035 - __main__ - INFO - ================================================================================
2025-11-23 20:00:57,048 - __main__ - INFO - Train set: 69080 (70.0%)
2025-11-23 20:00:57,049 - __main__ - INFO - Val set: 14803 (15.0%)
2025-11-23 20:00:57,049 - __main__ - INFO - Test set: 14804 (15.0%)
2025-11-23 20:00:57,050 - __main__ - INFO -
Train date range: 2019-05-27 15:54:42 to 2023-01-28 06:07:36
2025-11-23 20:00:57,051 - __main__ - INFO - Val date range: 2023-01-28 06:26:37 to 2023-08-12 10:47:20
2025-11-23 20:00:57,052 - __main__ - INFO - Test date range: 2023-08-12 10:47:20 to 2024-03-06 11:53:26
2025-11-23 20:00:57,054 - __main__ - INFO - ================================================================================
2025-11-23 20:00:57,054 - __main__ - INFO - PREPARING ARRAYS FOR ITEM-LEVEL PREDICTION
2025-11-23 20:00:57,055 - __main__ - INFO - ================================================================================
2025-11-23 20:00:57,228 - __main__ - INFO - X_train_seq shape: (69080, 5, 255)
2025-11-23 20:00:57,228 - __main__ - INFO -   (n_samples, sequence_length, n_items)
2025-11-23 20:00:57,229 - __main__ - INFO - X_train_context shape: (69080, 3)
2025-11-23 20:00:57,229 - __main__ - INFO - y_train shape: (69080,)
2025-11-23 20:00:57,229 - __main__ - INFO - ================================================================================
2025-11-23 20:00:57,229 - __main__ - INFO - STEP 3 COMPLETE
2025-11-23 20:00:57,229 - __main__ - INFO - ================================================================================
2025-11-23 20:00:57,232 - __main__ - INFO - Order-level sequences ready for model training

In [84]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
import logging
from typing import Tuple, Dict

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class OrderSequenceDataset(Dataset):
    
    def __init__(self, sequences: np.ndarray, context: np.ndarray, targets: np.ndarray, mode: str = 'item'):
        self.sequences = torch.FloatTensor(sequences)
        self.context = torch.FloatTensor(context)
        self.mode = mode
        
        if mode == 'item':
            self.targets = torch.LongTensor(targets)
        else:
            self.targets = torch.FloatTensor(targets)
        
    def __len__(self) -> int:
        return len(self.sequences)
    
    def __getitem__(self, idx: int) -> Tuple:
        return self.sequences[idx], self.context[idx], self.targets[idx]


class OrderGRURecommender(nn.Module):
    
    def __init__(self, n_items: int, hidden_dim: int = 128, n_layers: int = 2, 
                 dropout: float = 0.3, prediction_mode: str = 'item'):
        super(OrderGRURecommender, self).__init__()
        
        self.n_items = n_items
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers
        self.prediction_mode = prediction_mode
        
        self.gru = nn.GRU(
            input_size=n_items,
            hidden_size=hidden_dim,
            num_layers=n_layers,
            dropout=dropout if n_layers > 1 else 0,
            batch_first=True
        )
        
        self.dropout = nn.Dropout(dropout)
        
        self.fc1 = nn.Linear(hidden_dim + 3, 256)
        self.bn1 = nn.BatchNorm1d(256)
        
        self.fc2 = nn.Linear(256, 128)
        self.bn2 = nn.BatchNorm1d(128)
        
        self.fc_out = nn.Linear(128, n_items)
        
        total_params = sum(p.numel() for p in self.parameters() if p.requires_grad)
        logger.info(f"OrderGRURecommender initialized with {total_params:,} parameters")
        logger.info(f"  Input shape: (batch, sequence_length, {n_items})")
        logger.info(f"  Prediction mode: {prediction_mode}")
        
    def forward(self, x: torch.Tensor, context: torch.Tensor) -> torch.Tensor:
        gru_out, hidden = self.gru(x)
        
        last_hidden = hidden[-1]
        
        combined = torch.cat([last_hidden, context], dim=1)
        
        out = self.dropout(combined)
        out = F.relu(self.bn1(self.fc1(out)))
        out = self.dropout(out)
        out = F.relu(self.bn2(self.fc2(out)))
        out = self.dropout(out)
        
        logits = self.fc_out(out)
        
        if self.prediction_mode == 'basket':
            return torch.sigmoid(logits)
        else:
            return logits


class OrderLSTMRecommender(nn.Module):
    
    def __init__(self, n_items: int, hidden_dim: int = 128, n_layers: int = 2,
                 dropout: float = 0.3, prediction_mode: str = 'item'):
        super(OrderLSTMRecommender, self).__init__()
        
        self.n_items = n_items
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers
        self.prediction_mode = prediction_mode
        
        self.lstm = nn.LSTM(
            input_size=n_items,
            hidden_size=hidden_dim,
            num_layers=n_layers,
            dropout=dropout if n_layers > 1 else 0,
            batch_first=True
        )
        
        self.dropout = nn.Dropout(dropout)
        
        self.fc1 = nn.Linear(hidden_dim + 3, 256)
        self.bn1 = nn.BatchNorm1d(256)
        
        self.fc2 = nn.Linear(256, 128)
        self.bn2 = nn.BatchNorm1d(128)
        
        self.fc_out = nn.Linear(128, n_items)
        
        total_params = sum(p.numel() for p in self.parameters() if p.requires_grad)
        logger.info(f"OrderLSTMRecommender initialized with {total_params:,} parameters")
        
    def forward(self, x: torch.Tensor, context: torch.Tensor) -> torch.Tensor:
        lstm_out, (hidden, cell) = self.lstm(x)
        
        last_hidden = hidden[-1]
        
        combined = torch.cat([last_hidden, context], dim=1)
        
        out = self.dropout(combined)
        out = F.relu(self.bn1(self.fc1(out)))
        out = self.dropout(out)
        out = F.relu(self.bn2(self.fc2(out)))
        out = self.dropout(out)
        
        logits = self.fc_out(out)
        
        if self.prediction_mode == 'basket':
            return torch.sigmoid(logits)
        else:
            return logits


class OrderAttentionGRU(nn.Module):
    
    def __init__(self, n_items: int, hidden_dim: int = 128, n_layers: int = 2,
                 n_heads: int = 4, dropout: float = 0.3, prediction_mode: str = 'item'):
        super(OrderAttentionGRU, self).__init__()
        
        self.n_items = n_items
        self.hidden_dim = hidden_dim
        self.prediction_mode = prediction_mode
        
        self.gru = nn.GRU(
            input_size=n_items,
            hidden_size=hidden_dim,
            num_layers=n_layers,
            dropout=dropout if n_layers > 1 else 0,
            batch_first=True
        )
        
        self.attention = nn.MultiheadAttention(
            embed_dim=hidden_dim,
            num_heads=n_heads,
            dropout=dropout,
            batch_first=True
        )
        
        self.dropout = nn.Dropout(dropout)
        
        self.fc1 = nn.Linear(hidden_dim * 2 + 3, 256)
        self.bn1 = nn.BatchNorm1d(256)
        
        self.fc2 = nn.Linear(256, 128)
        self.bn2 = nn.BatchNorm1d(128)
        
        self.fc_out = nn.Linear(128, n_items)
        
        total_params = sum(p.numel() for p in self.parameters() if p.requires_grad)
        logger.info(f"OrderAttentionGRU initialized with {total_params:,} parameters")
        
    def forward(self, x: torch.Tensor, context: torch.Tensor) -> torch.Tensor:
        gru_out, hidden = self.gru(x)
        
        attn_out, attn_weights = self.attention(gru_out, gru_out, gru_out)
        
        last_hidden = hidden[-1]
        attn_pooled = torch.mean(attn_out, dim=1)
        
        combined = torch.cat([last_hidden, attn_pooled, context], dim=1)
        
        out = self.dropout(combined)
        out = F.relu(self.bn1(self.fc1(out)))
        out = self.dropout(out)
        out = F.relu(self.bn2(self.fc2(out)))
        out = self.dropout(out)
        
        logits = self.fc_out(out)
        
        if self.prediction_mode == 'basket':
            return torch.sigmoid(logits)
        else:
            return logits


class OrderModelTrainer:
    
    def __init__(self, model: nn.Module, prediction_mode: str = 'item',
                 device: str = 'cuda' if torch.cuda.is_available() else 'cpu'):
        self.model = model.to(device)
        self.device = device
        self.prediction_mode = prediction_mode
        self.logger = logger
        
        self.logger.info(f"Trainer initialized on device: {device}")
        self.logger.info(f"Prediction mode: {prediction_mode}")
        
    def train_epoch(self, train_loader: DataLoader, criterion: nn.Module,
                   optimizer: torch.optim.Optimizer) -> Tuple[float, float]:
        self.model.train()
        total_loss = 0
        correct = 0
        total = 0
        
        for sequences, context, targets in train_loader:
            sequences = sequences.to(self.device)
            context = context.to(self.device)
            targets = targets.to(self.device)
            
            optimizer.zero_grad()
            outputs = self.model(sequences, context)
            
            if self.prediction_mode == 'item':
                loss = criterion(outputs, targets)
                _, predicted = outputs.max(1)
                correct += predicted.eq(targets).sum().item()
            else:
                loss = criterion(outputs, targets)
                predicted = (outputs > 0.5).float()
                correct += (predicted == targets).all(dim=1).sum().item()
            
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)
            optimizer.step()
            
            total_loss += loss.item()
            total += targets.size(0)
        
        return total_loss / len(train_loader), 100. * correct / total
    
    def validate(self, val_loader: DataLoader, criterion: nn.Module) -> Tuple[float, float, float]:
        self.model.eval()
        total_loss = 0
        correct = 0
        top5_correct = 0
        total = 0
        
        with torch.no_grad():
            for sequences, context, targets in val_loader:
                sequences = sequences.to(self.device)
                context = context.to(self.device)
                targets = targets.to(self.device)
                
                outputs = self.model(sequences, context)
                
                if self.prediction_mode == 'item':
                    loss = criterion(outputs, targets)
                    _, predicted = outputs.max(1)
                    correct += predicted.eq(targets).sum().item()
                    
                    _, top5_pred = outputs.topk(5, 1, True, True)
                    top5_correct += top5_pred.eq(targets.view(-1, 1).expand_as(top5_pred)).sum().item()
                else:
                    loss = criterion(outputs, targets)
                    predicted = (outputs > 0.5).float()
                    correct += (predicted == targets).all(dim=1).sum().item()
                    top5_correct += correct
                
                total_loss += loss.item()
                total += targets.size(0)
        
        return total_loss / len(val_loader), 100. * correct / total, 100. * top5_correct / total
    
    def fit(self, train_loader: DataLoader, val_loader: DataLoader,
            epochs: int = 50, lr: float = 0.001, patience: int = 10) -> Dict:
        
        if self.prediction_mode == 'item':
            criterion = nn.CrossEntropyLoss()
        else:
            criterion = nn.BCELoss()
        
        optimizer = torch.optim.Adam(self.model.parameters(), lr=lr, weight_decay=1e-5)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode='min', factor=0.5, patience=5
        )
        
        best_val_loss = float('inf')
        patience_counter = 0
        history = {
            'train_loss': [], 'train_acc': [],
            'val_loss': [], 'val_acc': [], 'val_top5_acc': []
        }
        
        self.logger.info("="*80)
        self.logger.info("STARTING TRAINING")
        self.logger.info("="*80)
        
        for epoch in range(epochs):
            train_loss, train_acc = self.train_epoch(train_loader, criterion, optimizer)
            val_loss, val_acc, val_top5_acc = self.validate(val_loader, criterion)
            
            history['train_loss'].append(train_loss)
            history['train_acc'].append(train_acc)
            history['val_loss'].append(val_loss)
            history['val_acc'].append(val_acc)
            history['val_top5_acc'].append(val_top5_acc)
            
            scheduler.step(val_loss)
            
            self.logger.info(
                f"Epoch {epoch+1}/{epochs} | "
                f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}% | "
                f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.2f}% | "
                f"Val Top5 Acc: {val_top5_acc:.2f}%"
            )
            
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                patience_counter = 0
                self.best_model_state = self.model.state_dict()
            else:
                patience_counter += 1
            
            if patience_counter >= patience:
                self.logger.info(f"Early stopping triggered after {epoch+1} epochs")
                break
        
        self.model.load_state_dict(self.best_model_state)
        
        self.logger.info("="*80)
        self.logger.info("TRAINING COMPLETE")
        self.logger.info("="*80)
        
        return history
    
    def predict_top_k(self, sequence: np.ndarray, context: np.ndarray, top_k: int = 10) -> Tuple[np.ndarray, np.ndarray]:
        self.model.eval()
        
        with torch.no_grad():
            seq_tensor = torch.FloatTensor(sequence).unsqueeze(0).to(self.device)
            ctx_tensor = torch.FloatTensor(context).unsqueeze(0).to(self.device)
            
            output = self.model(seq_tensor, ctx_tensor)[0]
            
            if self.prediction_mode == 'item':
                top_k_scores, top_k_indices = torch.topk(output, top_k)
            else:
                top_k_indices = torch.argsort(output, descending=True)[:top_k]
                top_k_scores = output[top_k_indices]
            
            return top_k_indices.cpu().numpy(), top_k_scores.cpu().numpy()


if __name__ == "__main__":
    logger.info("UPDATED STEPS 6-7: PyTorch Models for Order Sequences")
    logger.info("")
    logger.info("Key Changes:")
    logger.info("  - Input shape: (batch, sequence_length, n_items)")
    logger.info("  - No embedding layer (orders are already one-hot)")
    logger.info("  - Context features added to final layer")
    logger.info("  - Supports both item and basket prediction modes")
    logger.info("")
    logger.info("Usage:")
    logger.info("  model = OrderGRURecommender(n_items=94, hidden_dim=128, prediction_mode='item')")
    logger.info("  trainer = OrderModelTrainer(model, prediction_mode='item')")
    logger.info("  history = trainer.fit(train_loader, val_loader, epochs=50)")

2025-11-23 20:04:39,682 - __main__ - INFO - UPDATED STEPS 6-7: PyTorch Models for Order Sequences
2025-11-23 20:04:39,682 - __main__ - INFO -
2025-11-23 20:04:39,682 - __main__ - INFO - Key Changes:
2025-11-23 20:04:39,682 - __main__ - INFO -   - Input shape: (batch, sequence_length, n_items)
2025-11-23 20:04:39,684 - __main__ - INFO -   - No embedding layer (orders are already one-hot)
2025-11-23 20:04:39,684 - __main__ - INFO -   - Context features added to final layer
2025-11-23 20:04:39,684 - __main__ - INFO -   - Supports both item and basket prediction modes
2025-11-23 20:04:39,684 - __main__ - INFO -
2025-11-23 20:04:39,684 - __main__ - INFO - Usage:
2025-11-23 20:04:39,684 - __main__ - INFO -   model = OrderGRURecommender(n_items=94, hidden_dim=128, prediction_mode='item')
2025-11-23 20:04:39,684 - __main__ - INFO -   trainer = OrderModelTrainer(model, prediction_mode='item')
2025-11-23 20:04:39,684 - __main__ - INFO -   history = trainer.fit(train_loader, val_loader, epochs=50)

In [85]:
model = OrderGRURecommender(n_items=94, hidden_dim=128, prediction_mode='item')

2025-11-23 20:04:46,238 - __main__ - INFO - OrderGRURecommender initialized with 264,670 parameters
2025-11-23 20:04:46,238 - __main__ - INFO -   Input shape: (batch, sequence_length, 94)
2025-11-23 20:04:46,238 - __main__ - INFO -   Prediction mode: item

In [87]:
trainer = OrderModelTrainer(model, prediction_mode='item')
history = trainer.fit(train_loader, val_loader, epochs=50)

2025-11-23 20:05:00,285 - __main__ - INFO - Trainer initialized on device: cpu
2025-11-23 20:05:00,286 - __main__ - INFO - Prediction mode: item

NameError: name 'train_loader' is not defined

In [91]:
arrays.items